Repository UKHomeOffice/hocs-casework, pull requests merged in 2022-08, with the labels that each got.

#704 HOCS-4791: Add ability to create POGR2 cases
  src/main/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyPOGRtoPOGR2.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyPOGRToPOGR2Test.java
Labels: minor

#709 HOCS-5438: Support multi arch builds
  Dockerfile
Labels: minor, smoketest

#713 HOCS-4803: Automatically assign POGR2 cases
  src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/CreateCaseResponse.java
  src/main/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyPOGRtoPOGR2.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyPOGRToPOGR2Test.java
Labels: minor

#718 HOCS-5465: add correspondent type name
  src/main/java/uk/gov/digital/ho/hocs/casework/api/CorrespondentService.java
  src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/CorrespondentWithPrimaryFlag.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/CorrespondentServiceTest.java
Labels: patch

#722 HOCS-5462: add equals and hash code
  src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/GetCaseSummaryResponse.java
  src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/AdditionalField.java
Labels: patch

#724 HOCS-5521: add missing POGR->POGR2 key
  src/main/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyPOGRtoPOGR2.java
Labels: patch

#725 Alter maxUnavailable to 0 based on prod experience
  kube/kd/deployment.yaml
Labels: patch
