Repository UKHomeOffice/hocs-casework, pull requests merged in 2022-10, with the labels that each got.

#750 HOCS-5519: add field to 'TO' summary and accordion
  src/main/resources/config/details/stages/TO.json
  src/main/resources/config/summary/TO.json
Labels: patch

#751 HOCS-5629: fix choices for accordion field
  src/main/resources/config/details/stages/IEDET.json
Labels: patch

#755 HOCS-5681: reconfigure accordion
  src/main/resources/config/details/stages/BF.json
  src/main/resources/config/details/stages/BF2.json
  src/main/resources/config/details/stages/COMP.json
  src/main/resources/config/details/stages/COMP2.json
  src/main/resources/config/details/stages/DTEN.json
  src/main/resources/config/details/stages/FOI.json
  src/main/resources/config/details/stages/IEDET.json
  src/main/resources/config/details/stages/MIN.json
  src/main/resources/config/details/stages/MPAM.json
  src/main/resources/config/details/stages/MTS.json
  src/main/resources/config/details/stages/POGR.json
  src/main/resources/config/details/stages/POGR2.json
  src/main/resources/config/details/stages/SMC.json
  src/main/resources/config/details/stages/TO.json
  src/main/resources/config/details/stages/TRO.json
Labels: patch

#756 HOCS-5632: IEDET - Complaint sub categories are not displayed correctly in Case Details accordion
  src/main/resources/config/details/stages/IEDET.json
Labels: patch

#759 Json changes to add new document types to POGR and POGR2 cases
  src/main/resources/config/document-tags/POGR.json
  src/main/resources/config/document-tags/POGR2.json
Labels: minor

#745 HOCS-5585: Migration audit
  src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseDataService.java
  src/main/java/uk/gov/digital/ho/hocs/casework/migration/client/auditclient/MigrationAuditClient.java
  src/main/resources/application-local.properties
  src/test/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseDataServiceTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/migration/client/auditclient/MigrationAuditClientTest.java
Labels: minor

#757 HOCS-5684: Add get case for team endpoint
  src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataResource.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataResourceTest.java
Labels: minor

#760 HOCS-5561: Use generic helm chart - Notprod memory bump
  helm/values-notprod.yaml
Labels: patch

#761 HOCS-5585: Add missing migration values to deployment
  helm/hocs-casework/templates/_envs.tpl
  helm/hocs-casework/values.yaml
Labels: patch

#762 HOCS-5664: Update IEDET complaint type choices
  src/main/resources/config/summary/IEDET.json
Labels: patch

#767 HOCS-5691: add DRAFT document tag
  src/main/resources/config/document-tags/IEDET.json
Labels: patch

#764 HOCS-5725: disable proxy image in dev only
  helm/hocs-casework/Chart.yaml
  helm/hocs-casework/templates/_envs.tpl
  helm/values-dev.yaml
Labels: minor, smoketest

#770 HOCS-5711: Copy correspondents field value
  src/main/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyBfToBf2.java
  src/main/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyCompToComp2.java
  src/main/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyPOGRtoPOGR2.java
  src/main/resources/config/details/stages/POGR2.json
  src/test/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyBfToBf2Test.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyCompToComp2Test.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyPOGRToPOGR2Test.java
Labels: minor

#771 Lower log level for Case Details Groups
  src/main/java/uk/gov/digital/ho/hocs/casework/domain/repository/CaseDataDetailsGroupsRepository.java
Labels: patch

#769 HOCS-5725: disable proxy image in notprod
  helm/values-dev.yaml
  helm/values-notprod.yaml
Labels: minor

#775 HOCS-5561: Update Memory to reflect Prod values
  helm/hocs-casework/values.yaml
Labels: patch

#780 HOCS-5833 resolve NPE when copying cases
  src/main/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyBfToBf2.java
  src/main/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyCompToComp2.java
  src/main/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyPOGRtoPOGR2.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyBfToBf2Test.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyCompToComp2Test.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyPOGRToPOGR2Test.java
Labels: patch

#782 HOCS-5847 - Updated IEDET json to fix the text
  src/main/resources/config/details/stages/IEDET.json
Labels: patch

#776 Hocs 5583 - create correspondent for migrated case
  src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseDataService.java
  src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseResource.java
  src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseService.java
  src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationStageService.java
  src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/dto/ComplaintCorrespondent.java
  src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/dto/CorrespondentType.java
  src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/dto/CreateMigrationCaseRequest.java
  src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/dto/MigrationComplaintCorrespondent.java
  src/test/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseDataServiceTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseResourceTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseServiceTest.java
Labels: minor
