Repository UKHomeOffice/hocs-casework, pull requests merged in 2022-05, with the labels that each got.

#646 HOCS-4596 add case action data filtering
  src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseActionsResource.java
  src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/GetCaseSummaryResponse.java
  src/main/java/uk/gov/digital/ho/hocs/casework/security/filters/GetCaseSummaryAuthFilterService.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseActionServiceIntegrationTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/security/filters/GetCaseSummaryAuthFilterServiceTest.java
Labels: minor

#657 HOCS-5027: add dependabot GitHub Action update
  .github/dependabot.yml
Labels: skip-release

#654 HOCS-4712: Change to the StageData view to help the Mpam teams
  src/main/java/uk/gov/digital/ho/hocs/casework/domain/repository/CaseDataRepository.java
  src/main/resources/db/migration/postgresql/V1_40__4235_RECREATE_STAGE_DATA.sql
Labels: patch

#656 HOCS-5000: stage duplication problem
  src/main/java/uk/gov/digital/ho/hocs/casework/api/StageResource.java
  src/main/java/uk/gov/digital/ho/hocs/casework/api/StageService.java
  src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/CreateStageRequest.java
  src/main/java/uk/gov/digital/ho/hocs/casework/domain/repository/StageRepository.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/StageResourceTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/StageServiceTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/dto/CreateStageRequestTest.java
Labels: patch

#652 HOCS-4409: Render tabs from DB
  src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataResource.java
  src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataService.java
  src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/GetCaseConfigResponse.java
  src/main/java/uk/gov/digital/ho/hocs/casework/application/LogEvent.java
  src/main/java/uk/gov/digital/ho/hocs/casework/client/infoclient/InfoClient.java
  src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/CaseConfig.java
  src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/CaseTab.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataServiceTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/client/infoclient/InfoClientTest.java
Labels: minor

#665 HOCS-5046: fix case admin user stage transition failure
  src/main/java/uk/gov/digital/ho/hocs/casework/api/StageService.java
Labels: patch

#673 HOCS-5032: Upgrade docker-compose and drone to use postgres 14
  .drone.yml
  docker-compose.yml
Labels: skip-release

#672 Chore: Upgrade drone build image version
  .drone.yml
Labels: skip-release

#674 HOCS-5140: Add G-Action Slack failure notification
  .github/workflows/semver.yml
Labels: skip-release
