Repository UKHomeOffice/hocs-casework, pull requests merged in 2022-11, with the labels that each got.

#785 HOCS-5854 - Accordion display changes
  src/main/resources/config/details/stages/IEDET.json
Labels: patch

#787 Change logging event for document tag
  src/main/java/uk/gov/digital/ho/hocs/casework/application/LogEvent.java
  src/main/java/uk/gov/digital/ho/hocs/casework/domain/repository/CaseTypeDocumentTagRepository.java
Labels: patch

#784 HOCS-5829 : Fixing inconsistent Camel/Sentence case use in IEDET Work…
  src/main/resources/config/details/stages/IEDET.json
  src/main/resources/config/summary/IEDET.json
Labels: minor

#793 HOCS-5918: PSU final response changes
  src/main/resources/config/details/stages/IEDET.json
  src/main/resources/config/summary/IEDET.json
Labels: patch

#797 HOCS-5503: Change IEDET categories screen
  src/main/resources/config/details/stages/IEDET.json
Labels: minor

#801 [HOCS-5694] Remove copying gender from COMP -> COMP2
  src/main/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyCompToComp2.java
Labels: patch

#800 HOCS-5920: rework tagging functionality
  src/main/java/uk/gov/digital/ho/hocs/casework/api/StageService.java
  src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/StageWithCaseData.java
  src/main/java/uk/gov/digital/ho/hocs/casework/domain/repository/CaseTagRepository.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/StageServiceTest.java
Labels: patch, smoketest

#803 HOCS-5538: IEDET PSU review categories
  src/main/resources/config/details/stages/IEDET.json
Labels: minor
