Repository UKHomeOffice/hocs-casework, pull requests merged in 2022-03, with the labels that each got.

#602 HOCS-4696: use GitHub SemVer actions
  .drone.yml
  .github/workflows/label-check.yml
  .github/workflows/semver.yml
Labels: major

#603 HOCS-4749: add linting/dry-run drone pipeline
  kube/.drone.yml
  kube/deploy.sh
Labels: patch

#601 HOCS-4682: pass through document values
  src/main/java/uk/gov/digital/ho/hocs/casework/client/documentclient/DocumentDto.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDocumentResourceTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDocumentServiceTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/client/documentclient/DocumentClientTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/security/filters/GetDocumentsAuthFilterServiceTest.java
Labels: minor

#608 HOCS-4696: Override Dependabot labels
  .github/dependabot.yml
Labels: patch

#605 HOCS-4716 BF2 Field auto population fix
  src/main/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyBfToBf2.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyBfToBf2Test.java
Labels: patch

#607 HOCS-4696: Remove duplicate Sonar Run.
  .drone.yml
Labels: patch

#600 HOCS-4221: Add ability to transfer BF cases to SMC
  src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDocumentService.java
  src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/CopyDocumentsRequest.java
  src/main/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyBFToCOMP.java
  src/main/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyBFToSMC.java
  src/main/java/uk/gov/digital/ho/hocs/casework/client/documentclient/DocumentClient.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyBFToCOMPTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyBFToSMCTest.java
Labels: minor

#612 HOCS-4455: BF2 Set CompType to service on escalate
  src/main/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyBfToBf2.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyBfToBf2Test.java
Labels: minor

#614 Hocs-4799: Update the base image to fix the drone build
  .drone.yml
Labels: patch

#615 HOCS-4808: support tagging on support branches
  .drone.yml
Labels: patch

#617 HOCS-4818: fix non displaying case reference after BF to SMC transfer
  src/main/java/uk/gov/digital/ho/hocs/casework/api/CorrespondentService.java
  src/main/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyBFToSMC.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyBFToSMCTest.java
Labels: patch
