Repository UKHomeOffice/hocs-casework, pull requests merged in 2022-04, with the labels that each got.

#625 HOCS-4862: update match label action version
  .github/workflows/pr-check.yml
  .github/workflows/semver.yml
Labels: skip-release

#630 Fix dependancy issues
  build.gradle
  src/main/resources/application.properties
Labels: patch

#635 HOCS-4863: update semver tag action release version
  .github/workflows/pr-check.yml
  .github/workflows/semver.yml
Labels: skip-release

#644 Remove db initialise initcontainer
  kube/kd/deployment.yaml
Labels: patch

#624 HOCS-3803: add suspend feature for smc cases
  src/main/java/uk/gov/digital/ho/hocs/casework/api/ActionDataDeadlineExtensionService.java
  src/main/java/uk/gov/digital/ho/hocs/casework/api/ActionDataSuspendService.java
  src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseActionService.java
  src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseActionsResource.java
  src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataService.java
  src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/ActionDataDto.java
  src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/ActionDataSuspendDto.java
  src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/GetCaseSummaryResponse.java
  src/main/java/uk/gov/digital/ho/hocs/casework/api/utils/CaseDeadlineHelpers.java
  src/main/java/uk/gov/digital/ho/hocs/casework/client/auditclient/AuditClient.java
  src/main/java/uk/gov/digital/ho/hocs/casework/client/auditclient/EventType.java
  src/main/java/uk/gov/digital/ho/hocs/casework/client/auditclient/dto/AuditPayload.java
  src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/AbstractCaseData.java
  src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/ActionDataSuspension.java
  src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/CaseSummary.java
  src/main/java/uk/gov/digital/ho/hocs/casework/domain/repository/SuspensionRepository.java
  src/main/java/uk/gov/digital/ho/hocs/casework/security/filters/GetCaseSummaryAuthFilterService.java
  src/main/resources/db/migration/postgresql/V1_39__3803_ADD_ACTION_SUSPENSION_TABLE.sql
  src/test/java/uk/gov/digital/ho/hocs/casework/api/ActionDataSuspendServiceTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseActionServiceIntegrationTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataResourceTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/dto/GetCaseSummaryResponseTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/utils/CaseDeadlineHelpersTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/client/auditclient/AuditClientTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/security/filters/GetCaseAuthFilterServiceTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/security/filters/GetCaseSummaryAuthFilterServiceTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/security/filters/GetDocumentsAuthFilterServiceTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/security/filters/TimelineItemAuthFilterServiceTest.java
  src/test/resources/action/afterTest.sql
  src/test/resources/action/beforeTest.sql
Labels: minor
