Repository UKHomeOffice/hocs-casework, pull requests merged in 2023-01, with the labels that each got.

#816 HOCS-5669: Add COMP serious details screen
  src/main/resources/config/details/stages/COMP.json
  src/main/resources/config/details/stages/COMP2.json
  src/main/resources/config/summary/COMP.json
  src/main/resources/config/summary/COMP2.json
Labels: minor

#830 Revert "HOCS-6121: Boyscout: remove deprecated/unused code for Major …
  src/main/java/uk/gov/digital/ho/hocs/casework/api/ActionDataAppealsService.java
  src/main/java/uk/gov/digital/ho/hocs/casework/api/ActionDataExternalInterestService.java
  src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDocumentService.java
  src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseProfileResource.java
  src/main/java/uk/gov/digital/ho/hocs/casework/api/DeadlineService.java
  src/main/java/uk/gov/digital/ho/hocs/casework/api/StageResource.java
  src/main/java/uk/gov/digital/ho/hocs/casework/api/StageService.java
  src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/ApplyExtensionRequest.java
  src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/BankHolidaysByRegionDto.java
  src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/GetCaseResponse.java
  src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/GetCasesForUserResponse.java
  src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/RecreateStageRequest.java
  src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/SomuTypeDto.java
  src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/UpdateStageTransitionNoteRequest.java
  src/main/java/uk/gov/digital/ho/hocs/casework/client/auditclient/AuditClient.java
  src/main/java/uk/gov/digital/ho/hocs/casework/client/infoclient/InfoClient.java
  src/main/java/uk/gov/digital/ho/hocs/casework/client/infoclient/InfoNominatedPeople.java
  src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/BankHoliday.java
  src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/CaseDeadlineExtension.java
  src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/CaseDeadlineExtensionType.java
  src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/CaseSummarySomuItems.java
  src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/CaseTab.java
  src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/Summary.java
  src/main/java/uk/gov/digital/ho/hocs/casework/domain/repository/ActionDataAppealsRepository.java
  src/main/java/uk/gov/digital/ho/hocs/casework/domain/repository/ActionDataDeadlineExtensionRepository.java
  src/main/java/uk/gov/digital/ho/hocs/casework/domain/repository/BankHolidayRepository.java
  src/main/java/uk/gov/digital/ho/hocs/casework/domain/repository/CaseDeadlineExtensionTypeRepository.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/ActionDataAppealsServiceTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/ActionDataDeadlineExtensionServiceTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/ActionDataExternalInterestServiceTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataDeadlinesIntegrationTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataDeleteCaseIntegrationTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataGetCaseSummaryIntegrationTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataServiceTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataTimelineCaseIntegrationTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDocumentServiceTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseNoteIntegrationTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseProfileResourceTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/CorrespondentResourceTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/CorrespondentServiceTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/DashboardServiceTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/DeadlineServiceTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/StageResourceTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/StageServiceTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/TopicsGetIntegrationTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/UpdateCorrespondentIntegrationTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/api/factory/CaseCopyFactoryTest.java
  src/test/java/uk/gov/digital/ho/hocs/casework/security/AuthorisationAspectTest.java
Labels: major

#818 HOCS-5728: Add PSU registration to COMP
  src/main/resources/config/details/stages/COMP.json
  src/main/resources/config/details/stages/COMP2.json
  src/main/resources/config/summary/COMP.json
  src/main/resources/config/summary/COMP2.json
Labels: minor

#831 HOCS-5729: PSU add final response screen
  src/main/resources/config/details/stages/COMP.json
  src/main/resources/config/details/stages/COMP2.json
Labels: minor

#836 HOCS-5672: Add PSU escalation point from triage conributions stage
  src/main/resources/config/details/stages/COMP.json
  src/main/resources/config/details/stages/COMP2.json
Labels: minor

#838 HOCS-6153- correct Complaint speeling in COMP stage2 phase
  src/main/resources/config/details/stages/COMP2.json
Labels: minor

#839 HOCS-6151: Group categories in comp registration
  src/main/resources/config/details/stages/COMP.json
  src/main/resources/config/details/stages/COMP2.json
Labels: minor

#840 HOCS-6159: Reorder COMP + IEDET accordions
  src/main/resources/config/details/stages/COMP.json
  src/main/resources/config/details/stages/COMP2.json
  src/main/resources/config/details/stages/IEDET.json
Labels: minor

#841 HOCS-6163- build changes to display Business unit type for BF cases
  src/main/resources/config/details/stages/TO.json
Labels: patch

#845 HOCS-6170-UI fixes for UKVI input fields
  src/main/resources/config/details/stages/COMP.json
  src/main/resources/config/summary/COMP.json
Labels: minor

#844 HOCS-6169: Group categories in COMP accordion
  src/main/resources/config/details/stages/COMP.json
  src/main/resources/config/details/stages/COMP2.json
Labels: minor

#853 HOCS-6183: Remove incorrect value from COMP accordion
  src/main/resources/config/details/stages/COMP.json
  src/main/resources/config/details/stages/COMP2.json
Labels: minor
